#!/usr/bin/env python3
from datetime import datetime

print('url:')
url = input()
print('title:')
title = input()
print('tags:')
tags = input()
print('body:')
body = input()
date = datetime.today().strftime("%Y-%m-%d")


with open("partials/links.html", "r+") as linksfile:
    posttext = """\
{{% link
"{0}"
"{1}"
"{2}" "{3}" %}}
{4}
{{% endlink %}}""".format(title, url, date, tags, body)

    content = linksfile.read()
    linksfile.seek(0, 0)
    linksfile.write(posttext + "\n\n" + content)
